export const data = [
    { key: "A", value: -30, channel: "X" },
    { key: "B", value: -80, channel: "Y" },
    { key: "C", value: -45, channel: "X" },
    { key: "D", value: -60, channel: "Z" },
    { key: "E", value: -20, channel: "Y" },
    { key: "F", value: -90, channel: "X" },
    { key: "G", value: -55, channel: "Z" },
    { key: "H", value: -35, channel: "X" },
    { key: "I", value: -75, channel: "Y" },
    { key: "J", value: -50, channel: "Z" },
    { key: "K", value: 30, channel: "X" },
    { key: "L", value: 80, channel: "Y" },
    { key: "M", value: 45, channel: "X" },
    { key: "N", value: 60, channel: "Z" },
    { key: "O", value: 20, channel: "Y" },
    { key: "P", value: 90, channel: "X" },
    { key: "Q", value: 55, channel: "Z" },
    { key: "R", value: 35, channel: "X" },
    { key: "S", value: 75, channel: "Y" },
    { key: "T", value: 50, channel: "Z" },
    { key: "U", value: 25, channel: "X" },
    { key: "V", value: 85, channel: "Y" },
    { key: "W", value: 40, channel: "X" },
    { key: "X", value: 65, channel: "Z" },
    { key: "Y", value: 15, channel: "Y" }
];
